INSERT INTO categoria VALUES(1,'Acción',true);
INSERT INTO categoria VALUES(2,'Aventuras',true);
INSERT INTO categoria VALUES(3,'Ciencia Ficción',true);
INSERT INTO categoria VALUES(4,'Comedia',true);
INSERT INTO categoria VALUES(5,'Crimen',true);
INSERT INTO categoria VALUES(6,'Drama',true);
INSERT INTO categoria VALUES(7,'Epico',true);
INSERT INTO categoria VALUES(8,'Espionaje',true);
INSERT INTO categoria VALUES(9,'Familiar',true);
INSERT INTO categoria VALUES(10,'Fantasía',true);
INSERT INTO categoria VALUES(11,'Guerra',true);
INSERT INTO categoria VALUES(12,'Histórica',true);
INSERT INTO categoria VALUES(13,'Misterio',true);
INSERT INTO categoria VALUES(14,'Musical',true);
INSERT INTO categoria VALUES(15,'Western',true);
INSERT INTO categoria VALUES(16,'Romance',true);
INSERT INTO categoria VALUES(17,'Suspenso',true);
INSERT INTO categoria VALUES(18,'Terror',true);
INSERT INTO categoria VALUES(19,'Vanguardia',true);
INSERT INTO categoria VALUES(20,'Documental',true);
INSERT INTO categoria VALUES(21,'Cortometraje',true);
INSERT INTO categoria VALUES(22,'Biográfica',true);
INSERT INTO categoria VALUES(23,'Drama Musical',true);
INSERT INTO categoria VALUES(24,'Drama Fantástico',true);
INSERT INTO categoria VALUES(25,'Drama Deportivo',true);
INSERT INTO categoria VALUES(26,'Drama Bélico',true);
INSERT INTO categoria VALUES(27,'Drama Histórico',true);
INSERT INTO categoria VALUES(28,'Animación',true);
INSERT INTO categoria VALUES(29,'Comedia Romántica',true);
INSERT INTO categoria VALUES(30,'Drama Romántico',true);
INSERT INTO categoria VALUES(32,'Comedia Fantástica',true);
INSERT INTO categoria VALUES(33,'Drama Biográfico',true);
INSERT INTO categoria VALUES(34,'Comedia Drama Romance',true);
INSERT INTO categoria VALUES(35,'Comedia Drama',true);
INSERT INTO categoria VALUES(36,'Comedia Musical',true);
INSERT INTO categoria VALUES(37,'Drama Criminal',true);
INSERT INTO categoria VALUES(38,'Comedia Suspenso',true);
INSERT INTO categoria VALUES(39,'Comedia Ciencia Ficción',true);
INSERT INTO categoria VALUES(40,'Acción Comedia',true);
INSERT INTO categoria VALUES(41,'Aventuras Comedia',true);
INSERT INTO categoria VALUES(42,'Acción Ciencia Ficción',true);
INSERT INTO categoria VALUES(43,'Misterio Suspenso',true);
INSERT INTO categoria VALUES(44,'Drama Suspenso',true);
INSERT INTO categoria VALUES(45,'Comedia Familiar',true);
INSERT INTO categoria VALUES(46,'Acción Aventuras',true);
INSERT INTO categoria VALUES(47,'Crimen Suspenso',true);
INSERT INTO categoria VALUES(48,'Accion Fantasía',true);
INSERT INTO categoria VALUES(49,'Drama Judicial',true);
INSERT INTO categoria VALUES(50,'Aventuras Drama',true);
INSERT INTO categoria VALUES(51,'Aventuras Fantasia',true);
INSERT INTO categoria VALUES(52,'Accion Crimen',true);
INSERT INTO categoria VALUES(53,'Accion Suspenso',true);
INSERT INTO categoria VALUES(54,'Fantasia Aventuras',true);
INSERT INTO categoria VALUES(55,'Terror Suspenso',true);
INSERT INTO categoria VALUES(56,'Drama Comedia',true);
INSERT INTO categoria VALUES(57,'Crimen Accion',true);
INSERT INTO categoria VALUES(58,'Comedia Misterio',true);
INSERT INTO categoria VALUES(59,'Drama Misterio',true);
INSERT INTO categoria VALUES(60,'Crimen Drama',true);
INSERT INTO categoria VALUES(61,'Aventuras Romance',true);
INSERT INTO categoria VALUES(62,'Drama Acción',true);
INSERT INTO categoria VALUES(63,'Acción Drama',true);
INSERT INTO categoria VALUES(64,'Comedia Crimen',true);
INSERT INTO categoria VALUES(65,'Crimen Comedia',true);
INSERT INTO categoria VALUES(66,'Acción Horror',true);
INSERT INTO categoria VALUES(67,'Terror Fantasía',true);
INSERT INTO categoria VALUES(68,'Acción Romance',true);
INSERT INTO categoria VALUES(69,'Comedia Western',true);
INSERT INTO categoria VALUES(70,'Comedia Acción',true);
INSERT INTO categoria VALUES(71,'Erotico',true);
INSERT INTO categoria VALUES(0,'No definido',true);
